### ISSUE TITLE
Persisting dev team in package.json

### ISSUE THREAD

**Issue by DaKaZ** [rhdeck/react-native-setdevteam#1]
@rhdeck I notice that this package does not persist the dev team choice to package.json.  I am attempting to setup our project so that if a user:
```
rm -rf ios
react-native eject
react-native link
```
It just works.  Is there any reason you chose to not persist this value?

**Comment by rhdeck** [comment]
Fixed in 1.2. Dev team is now persisted in `package.json`. Re-running  `react-native setdevteam` will pull the dev team listed in the package.json without looking at `.rninfo`. 

This meshes with issue #2 (fixed in 1.3) that takes care of applying the development team as a react-native link hook, so you don't need to run the plugin every time.
